version: '3.8'

services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    ports:
      - "7687:7687"
      - "7444:7444"  # HTTP endpoint
    volumes:
      - memgraph_data:/var/lib/memgraph
    command: ["--also-log-to-stderr", "--auth-module-mappings="]

  memgraph-lab:
    image: memgraph/lab:latest
    ports:
      - "3001:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
      - QUICK_CONNECT_MG_USERNAME=
      - QUICK_CONNECT_MG_PASSWORD=

volumes:
  memgraph_data: